---
name: 'Run golangci-lint'
description: 'Official golangci-lint runner. Works very fast: uses caching and parallelization. Creates line-attached GitHub annotations for found issues. Beta version.'
author: 'golangci'
inputs:
  version:
    description: 'version of golangci-lint to use in form of v1.2.3'
    required: true
  args:
    description: 'golangci-lint command line arguments'
    default: ''
    required: false
  github-token:
    description: 'GitHub token with scope `repo.public_repo`. Used for fetching a list of releases of golangci-lint.'
    required: true

runs:
  using: 'node12'
  main: 'dist/run/index.js'
  post: 'dist/post_run/index.js'
branding:
  icon: 'shield'
  color: 'yellow'
