---
name: 'Run golangci-lint'
description: 'Run golangci-lint (WIP)'
author: 'golangci'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  flags:
    description: 'GolangCI command line flags'
    required: false
  directory:
    description: 'Working directory'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-circle'
  color: 'blue'
