name: golangci
on: [pull_request]
jobs:
  golangci-lint-dockerfile:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: ./
        with:
          directory: sample
          format: colored-line-number
          flags: --issues-exit-code 0
