name: golangci-lint
on: [pull_request]
jobs:
  golangci-lint-dockerfile:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          flags: "./testdata"
